permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title : ilastik
author :
  name : the ilastik developers 
  email : ilastik-user@ilastik.org
  github : ilastik

production_url : http://ilastik.github.io
baseurl: http://ilastik.github.io
relative_permalinks: false
